### ISSUE TITLE
Question: Does container support all functionalities of Apama ?

### ISSUE THREAD

**Issue by peterlamar** [SoftwareAG/apama-streaming-analytics-docker-samples#26]
Does container support all functionalities of Apama ?

**Comment by CaribouJohn** [comment]
Hi Peter, we have 2 images that cover the fucntionality of Apama, but the basic answer is yes (for the version you choose)  

https://hub.docker.com/publishers/softwareag 

We have Apama-Correlator and Apama-Builder. The builder is meant to allow you to build your own Apama application images and Apama-Correlator is the base image. 

What specifically do you need ? 

You can check here for extra information : http://www.apamacommunity.com/documents/10.3.1.1/apama_10.3.1.1_webhelp/apama-webhelp/ or since you are part of softwareAG you could ping me directly and I'll endevour to help.  john.heath@softwareag.com.

**Comment by peterlamar** [comment]
Thats great, thanks!
